#!/usr/bin/venv python3

import os
import yaml
import shutil
import logging
import exifread

logging.basicConfig(level=logging.INFO, format = '%(asctime)s - %(levelname)s - %(message)s')

def moveFile(file_path, device_folder):
    try:
        if not os.path.exists(device_folder):
            os.makedirs(device_folder)
        shutil.move(file_path, device_folder)
        logging.info(f'file {file_path} moved to {device_folder}\n')

    except Exception as e:
        logging.error(f'file {file_path} to {device_folder}: {e}\n')

def deviceInfo(fext, file_path, folder_path):
    try:
        if fext.lower() in ('.jpeg', '.jpg', '.png', '.gif', '.heic'):
            with open(file_path, 'rb') as f:
                tags = exifread.process_file(f)
                model = tags.get('Image Model', None)

                if model:
                        model_str = str(model).strip().replace(' ', '_')
                        return os.path.join(folder_path, model_str)
                else:
                        return os.path.join(folder_path, 'unknown_source')
                
        elif fext.lower() in ('.mp4', '.avi', '.mov'):
            return os.path.join(folder_path, 'videos')
        
        else:
            logging.info(f'{file_path} not image/video\n')
            return None

    except Exception as e:
        logging.error(f'processing file {file_path}: {e}\n')
        return None

def processingFile(folder_path):
    for file in os.listdir(folder_path):
        _, fext = os.path.splitext(file)
        file_path = os.path.join(folder_path, file)

        if os.path.isfile(file_path):
                logging.info(f'processing file {file_path}')
                device_folder = deviceInfo(fext, file_path, folder_path)
                if device_folder is not None:
                    moveFile(file_path, device_folder)

def configFolder(folder_path = None):
	if folder_path is None:
		folder_path = os.path.join(os.path.expanduser("~"), 'Downloads')
	try:
		with open('config.yaml') as f:
			config = yaml.safe_load(f)

		folder_path = os.path.expandvars(config.get('paths', {}).get('folder_path'))
		if not folder_path:
			logging.error('failed to expand environment variable')

		processingFile(folder_path)

	except Exception as e:
		logging.error('error getting folder path')

configFolder()
